networks:
  laravel:
    external: true

services:

  symfony2601:
    container_name: symfony2601
    cpus: "0.15"
    networks:
      - laravel
    expose:
      - 9000
    build:
      context: .
      dockerfile: Symfony2601.Dockerfile
    working_dir: ${FOLDER_SYMFONY2601_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_SYMFONY2601_SERV}
    restart: unless-stopped
    volumes:
      - '${FOLDER_SYMFONY2601}:${FOLDER_SYMFONY2601_SERV}'
    deploy:
      resources:
        limits:
          cpus: '0.15'


  2602test_laravel:
    container_name: 2602test_laravel
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.2602laravel.Dockerfile
    working_dir: ${FOLDER_2602LARAVEL_TEST_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_2602LARAVEL_TEST_SERV}
    restart: unless-stopped
    volumes:
      - '${FOLDER_2602LARAVEL_TEST}:${FOLDER_2602LARAVEL_TEST_SERV}'
    healthcheck:
      test: ["CMD", "php", "artisan", "about", "--no-interaction"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 1G
        reservations:
          memory: 256M


  2603test_logistic:
    container_name: 2603test_logistic
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.2602laravel_logistic.Dockerfile
    working_dir: ${FOLDER_2603LOGISTIC_TEST_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_2603LOGISTIC_TEST_TEST}
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - '${FOLDER_2603LOGISTIC_TEST_TEST}:${FOLDER_2603LOGISTIC_TEST_SERV}'
    shm_size: 1gb
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 512M
        reservations:
          memory: 256M


  parser:
    container_name: parser_playwright
    cpus: "0.15"
    build: ./parser
    #      context: ./praser
    #      dockerfile: docker.parser.Dockerfile
    shm_size: 256mb
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 512M
