name: Deploy to VPS with Git


# Триггеры запуска:
on:
  # Автоматический запуск при пуше в main
  push:
    branches: [main]
  workflow_dispatch:

env:
  VPS_HOST: 91.218.230.97
  VPS_USERNAME: root
  DIR: /home/test_docker_ihc
  GIT_BRANCH: origin/main
  GITHUB_USERNAME: nyosru
  GIT_REPO: test_docker_ihc.git

jobs:
  sms_start:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment start notification
        uses: appleboy/telegram-action@master
        with:
          to: 360209578, phpcat
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀🚀🚀 Начинаем деплой ${{ github.repository }}
            👨🏻‍💻 ${{ github.actor }} (${{ github.run_id }})
            📝 ${{ github.event.head_commit.message }}


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY_DOCKER24 }}
          script: |
            set -e  # Выход при ошибке
            cd ${{ env.DIR }}
            git fetch --all
            git reset --hard ${{ env.GIT_BRANCH }}
            echo "✅ Код успешно обновлен"
            make prod
            echo "✅ Код успешно собран"
#            docker exec 2602test_laravel composer i
#            docker exec 2602test_laravel php artisan migrate
#            docker exec 2602test_laravel npm i
#            docker exec 2602test_laravel npm run build


  sms_end:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send deployment success notification
        uses: appleboy/telegram-action@master
        with:
          to: 360209578, phpcat
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🍀🍀🍀 Успешный деплой ${{ github.repository }}
            👨🏻‍💻 ${{ github.actor }} > ${{ github.run_id }}
            📝 ${{ github.event.head_commit.message }}
            🎉 Все задачи выполнены!
